Comment:
  type: entity
  table: comments
  fields:
    id:
      id: true
      type: integer
      length: '4'
      generator:
        strategy: AUTO
    author_id:
      type: integer
      length: '4'
      notnull: true
    teammatch_id:
      type: integer
      length: '4'
      notnull: true
    match_id:
      type: integer
      length: '4'
      notnull: false
    title:
      type: string
      length: '100'
      notnull: true
    message:
      type: text
      notnull: true
  oneToMany:
    Author:
      targetEntity: User
      cascade: {  }
      mappedBy: Comments
      inversedBy: null
      orphanRemoval: false
      orderBy: null
    Teammatch:
      targetEntity: Teammatch
      cascade: {  }
      mappedBy: Comments
      inversedBy: null
      orphanRemoval: false
      orderBy: null
  lifecycleCallbacks: {  }
