Game:
  type: entity
  table: games
  uniqueConstraints:
    game_index:
      columns:
        - annulled
        - game_sequence
        - match_id
  fields:
    id:
      id: true
      type: integer
      length: '4'
      generator:
        strategy: AUTO
    match_id:
      type: integer
      length: '4'
      notnull: true
    game_sequence:
      type: integer
      length: '1'
      notnull: true
    team1_score:
      type: integer
      length: '1'
      notnull: true
    team2_score:
      type: integer
      length: '1'
      notnull: true
    annulled:
      type: boolean
      notnull: true
  oneToMany:
    Match:
      targetEntity: Match
      cascade: {  }
      mappedBy: Games
      inversedBy: null
      orphanRemoval: false
      orderBy: null
  lifecycleCallbacks: {  }
