League:
  type: entity
  table: leagues
  uniqueConstraints:
    league_index:
      columns:
        - season
        - league_abbr
        - division
  fields:
    id:
      id: true
      type: integer
      length: '4'
      generator:
        strategy: AUTO
    season:
      type: string
      length: '10'
      notnull: true
    league_abbr:
      type: string
      length: '10'
      notnull: true
    league_name:
      type: string
      length: '50'
      notnull: true
    division:
      type: integer
      length: '1'
      notnull: true
    level:
      type: integer
      length: '1'
      notnull: true
    promoted_number:
      type: integer
      length: '1'
      notnull: true
    relegated_number:
      type: integer
      length: '1'
      notnull: true
  lifecycleCallbacks: {  }
