Location:
  type: entity
  table: locations
  uniqueConstraints:
    location_code_index:
      columns:
        - code
  fields:
    id:
      id: true
      type: integer
      length: '4'
      generator:
        strategy: AUTO
    code:
      type: string
      length: '10'
      notnull: true
    zip:
      type: string
      length: '10'
      notnull: true
    city:
      type: string
      length: '70'
      notnull: true
    street:
      type: string
      length: '70'
      notnull: true
    latitude:
      type: string
      length: '10'
      notnull: true
    longitude:
      type: string
      length: '10'
      notnull: true
    description:
      type: text
  lifecycleCallbacks: {  }
