Match:
  type: entity
  table: matches
  fields:
    id:
      id: true
      type: integer
      length: '4'
      generator:
        strategy: AUTO
    teammatch_id:
      type: integer
      length: '4'
      notnull: true
    match_type:
      type: string
      length: '10'
      notnull: true
    team1_player_id:
      type: integer
      length: '4'
      notnull: false
    team1_partner_id:
      type: integer
      length: '4'
      notnull: false
    team2_player_id:
      type: integer
      length: '4'
      notnull: false
    team2_partner_id:
      type: integer
      length: '4'
      notnull: false
    team1_score:
      type: integer
      length: '1'
      notnull: false
    team2_score:
      type: integer
      length: '1'
      notnull: false
    team1_points:
      type: integer
      length: '2'
      notnull: true
    team2_points:
      type: integer
      length: '2'
      notnull: true
    no_fight:
      type: boolean
      notnull: true
    withdrawn_by:
      type: integer
      length: '1'
      notnull: true
    revised_score:
      type: boolean
      notnull: true
    team1_original_score:
      type: integer
      length: '1'
      notnull: false
    team2_original_score:
      type: integer
      length: '1'
      notnull: false
    team1_original_points:
      type: integer
      length: '2'
      notnull: false
    team2_original_points:
      type: integer
      length: '2'
      notnull: false
    avg_orig_smaller_div_bigger_gamescore_permil:
      type: integer
      length: '2'
      notnull: false
    std_orig_smaller_div_bigger_gamescore_permil:
      type: integer
      length: '2'
      notnull: false
  oneToMany:
    Teammatch:
      targetEntity: Teammatch
      cascade: {  }
      mappedBy: Matches
      inversedBy: null
      orphanRemoval: false
      orderBy: null
    Team1_Player:
      targetEntity: Athlete
      cascade: {  }
      mappedBy: Matches
      inversedBy: null
      orphanRemoval: false
      orderBy: null
    Team1_Partner:
      targetEntity: Athlete
      cascade: {  }
      mappedBy: Matches
      inversedBy: null
      orphanRemoval: false
      orderBy: null
    Team2_Player:
      targetEntity: Athlete
      cascade: {  }
      mappedBy: Matches
      inversedBy: null
      orphanRemoval: false
      orderBy: null
    Team2_Partner:
      targetEntity: Athlete
      cascade: {  }
      mappedBy: Matches
      inversedBy: null
      orphanRemoval: false
      orderBy: null
  manyToMany:
    Games:
      targetEntity: Game
      cascade: {  }
      mappedBy: Match
      inversedBy: null
      joinTable: null
      orderBy: null
  lifecycleCallbacks: {  }
