Ratinghistory:
  type: entity
  table: ratinghistory
  indexes:
    created_at_index:
      columns:
        - created_at
  fields:
    id:
      id: true
      type: integer
      length: '4'
      generator:
        strategy: AUTO
    athlete_id:
      type: integer
      length: '4'
      notnull: true
    discipline:
      type: string
      notnull: true
    rating:
      type: integer
      length: '2'
      notnull: false
    number_matches:
      type: integer
      length: '2'
      notnull: true
  oneToMany:
    Athlete:
      targetEntity: Athlete
      cascade: {  }
      mappedBy: OldRatings
      inversedBy: null
      orphanRemoval: false
      orderBy: null
  lifecycleCallbacks: {  }
