Team:
  type: entity
  table: teams
  uniqueConstraints:
    team_index:
      columns:
        - team_number
        - league_id
        - club_id
  fields:
    id:
      id: true
      type: integer
      length: '4'
      generator:
        strategy: AUTO
    club_id:
      type: integer
      length: '4'
      notnull: true
    team_number:
      type: integer
      length: '1'
      notnull: true
    league_id:
      type: integer
      length: '4'
      notnull: true
    withdrawn:
      type: boolean
      notnull: true
    description:
      type: text
  oneToMany:
    Club:
      targetEntity: Club
      cascade: {  }
      mappedBy: Teams
      inversedBy: null
      orphanRemoval: false
      orderBy: null
    League:
      targetEntity: League
      cascade: {  }
      mappedBy: Teams
      inversedBy: null
      orphanRemoval: false
      orderBy: null
  lifecycleCallbacks: {  }
