User:
  type: entity
  table: users
  uniqueConstraints:
    username_index:
      columns:
        - username
  fields:
    id:
      id: true
      type: integer
      length: '4'
      generator:
        strategy: AUTO
    username:
      type: string
      length: '50'
      notnull: true
    email:
      type: string
      length: '255'
      notnull: true
    athlete_id:
      type: integer
      length: '4'
      notnull: false
  oneToOne:
    Athlete:
      targetEntity: Athlete
      cascade: {  }
      mappedBy: User
      inversedBy: null
      joinColumns:
        athlete_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
