Tobion\TropaionBundle\Entity\Teammatch:
    properties:
        team1_score:
            - NotBlank: ~
        #Matches:
            #- Valid: ~

Tobion\TropaionBundle\Entity\Match:
    constraints:
        - Tobion\TropaionBundle\Validator\Constraints\AthletesSpecified: ~
        - Tobion\TropaionBundle\Validator\Constraints\BadmintonResult: ~
        - Tobion\TropaionBundle\Validator\Constraints\ResultIncidentRevaluation: ~
