Lineups:
  type: entity
  table: lineups
  fields:
    teamId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: team_id
    seasonRound:
      id: true
      type: boolean
      nullable: false
      column: season_round
    athleteId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: athlete_id
    position:
      type: boolean
      nullable: false
  oneToOne:
    athlete:
      targetEntity: Athletes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        athlete_id:
          referencedColumnName: id
      orphanRemoval: false
    team:
      targetEntity: Teams
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        team_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
