Locations:
  type: entity
  table: locations
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    code:
      type: string
      length: 10
      fixed: false
      nullable: false
    zip:
      type: string
      length: 10
      fixed: false
      nullable: false
    city:
      type: string
      length: 70
      fixed: false
      nullable: false
    street:
      type: string
      length: 70
      fixed: false
      nullable: false
    latitude:
      type: string
      length: 10
      fixed: false
      nullable: false
    longitude:
      type: string
      length: 10
      fixed: false
      nullable: false
    description:
      type: text
      nullable: true
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  lifecycleCallbacks: {  }
