Ratinghistory:
  type: entity
  table: ratinghistory
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    discipline:
      type: string
      length: 7
      fixed: true
      nullable: false
    rating:
      type: smallint
      nullable: true
    numberMatches:
      type: smallint
      nullable: false
      column: number_matches
    createdAt:
      type: date
      nullable: false
      column: created_at
  oneToOne:
    athlete:
      targetEntity: Athletes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        athlete_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
