Teams:
  type: entity
  table: teams
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    teamNumber:
      type: boolean
      nullable: false
      column: team_number
    withdrawn:
      type: boolean
      nullable: false
    description:
      type: text
      nullable: true
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToOne:
    club:
      targetEntity: Clubs
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        club_id:
          referencedColumnName: id
      orphanRemoval: false
    league:
      targetEntity: Leagues
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        league_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
