Teammatches:
  type: entity
  table: teammatches
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    scheduledAt:
      type: datetime
      nullable: false
      column: scheduled_at
    performedAt:
      type: datetime
      nullable: false
      column: performed_at
    seasonRound:
      type: boolean
      nullable: false
      column: season_round
    team1Score:
      type: boolean
      nullable: true
      column: team1_score
    team2Score:
      type: boolean
      nullable: true
      column: team2_score
    team1Games:
      type: boolean
      nullable: true
      column: team1_games
    team2Games:
      type: boolean
      nullable: true
      column: team2_games
    team1Points:
      type: smallint
      nullable: true
      column: team1_points
    team2Points:
      type: smallint
      nullable: true
      column: team2_points
    noFight:
      type: boolean
      nullable: false
      column: no_fight
    annulled:
      type: boolean
      nullable: false
    revisedScore:
      type: boolean
      nullable: false
      column: revised_score
    wrongdoer:
      type: boolean
      nullable: false
    wrongdoingReason:
      type: boolean
      nullable: false
      column: wrongdoing_reason
    incompleteLineup:
      type: boolean
      nullable: false
      column: incomplete_lineup
    submittedAt:
      type: datetime
      nullable: true
      column: submitted_at
    confirmedAt:
      type: datetime
      nullable: true
      column: confirmed_at
    approvedAt:
      type: datetime
      nullable: true
      column: approved_at
    description:
      type: text
      nullable: true
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToOne:
    approvedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        approved_by_id:
          referencedColumnName: id
      orphanRemoval: false
    confirmedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        confirmed_by_id:
          referencedColumnName: id
      orphanRemoval: false
    location:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        location_id:
          referencedColumnName: id
      orphanRemoval: false
    submittedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        submitted_by_id:
          referencedColumnName: id
      orphanRemoval: false
    team1:
      targetEntity: Teams
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        team1_id:
          referencedColumnName: id
      orphanRemoval: false
    team2:
      targetEntity: Teams
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        team2_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
