Users:
  type: entity
  table: users
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    username:
      type: string
      length: 50
      fixed: false
      nullable: false
    email:
      type: string
      length: 255
      fixed: false
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToOne:
    athlete:
      targetEntity: Athletes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        athlete_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
